package xyz.x3ofiz4.exvia.presentation.notification

import android.Manifest
import android.app.Activity
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.content.pm.PackageManager
import android.os.Build
import android.app.Notification

/** Thin Android API wrapper. Rules/scripts remain outside this class. */
class NotificationDispatcher(private val activity: Activity) {
    private val manager = activity.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    init { if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) createChannel() }

    fun ensurePermission() {
        if (Build.VERSION.SDK_INT >= 33 && activity.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
            activity.requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQUEST_CODE)
        }
    }

    fun post(title: String, body: String, severity: String = "normal") {
        ensurePermission()
        if (Build.VERSION.SDK_INT >= 33 && activity.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) return
        val icon = android.R.drawable.stat_notify_more
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) Notification.Builder(activity, CHANNEL_ID) else Notification.Builder(activity)
        builder.setSmallIcon(icon).setContentTitle(title).setContentText(body).setStyle(Notification.BigTextStyle().bigText(body)).setAutoCancel(true)
        if (severity.equals("red",true) || severity.equals("warning",true)) builder.setCategory(Notification.CATEGORY_ERROR)
        manager.notify((System.currentTimeMillis() and 0x7fffffff).toInt(), builder.build())
    }

    private fun createChannel() {
        manager.createNotificationChannel(NotificationChannel(CHANNEL_ID, "Exvia notifications", NotificationManager.IMPORTANCE_DEFAULT).apply {
            description = "Assistant responses and notifications generated by Exvia event scripts"
        })
    }

    companion object { const val CHANNEL_ID="exvia_automation"; const val REQUEST_CODE=7316 }
}
